package paymentgateway;


/**
* paymentgateway/SecurePaymentProcessor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PaymentGatewayDefinition.idl
* Saturday, March 16, 2019 7:29:15 PM GMT
*/

public interface SecurePaymentProcessor extends SecurePaymentProcessorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SecurePaymentProcessor
