package paymentgateway;


/**
* paymentgateway/SecurePaymentProcessorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PaymentGatewayDefinition.idl
* Saturday, March 16, 2019 7:29:15 PM GMT
*/

public interface SecurePaymentProcessorOperations 
{
  String processPayment (String account_number, String iban, String amount);
  void shutdown ();
} // interface SecurePaymentProcessorOperations
