package paymentgateway;


/**
* paymentgateway/SecurePaymentProcessorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PaymentGatewayDefinition.idl
* Saturday, March 16, 2019 7:29:15 PM GMT
*/

abstract public class SecurePaymentProcessorHelper
{
  private static String  _id = "IDL:paymentgateway/SecurePaymentProcessor:1.0";

  public static void insert (org.omg.CORBA.Any a, paymentgateway.SecurePaymentProcessor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static paymentgateway.SecurePaymentProcessor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (paymentgateway.SecurePaymentProcessorHelper.id (), "SecurePaymentProcessor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static paymentgateway.SecurePaymentProcessor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SecurePaymentProcessorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, paymentgateway.SecurePaymentProcessor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static paymentgateway.SecurePaymentProcessor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof paymentgateway.SecurePaymentProcessor)
      return (paymentgateway.SecurePaymentProcessor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      paymentgateway._SecurePaymentProcessorStub stub = new paymentgateway._SecurePaymentProcessorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static paymentgateway.SecurePaymentProcessor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof paymentgateway.SecurePaymentProcessor)
      return (paymentgateway.SecurePaymentProcessor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      paymentgateway._SecurePaymentProcessorStub stub = new paymentgateway._SecurePaymentProcessorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
