package paymentgateway;

/**
* paymentgateway/SecurePaymentProcessorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PaymentGatewayDefinition.idl
* Saturday, March 16, 2019 7:29:15 PM GMT
*/

public final class SecurePaymentProcessorHolder implements org.omg.CORBA.portable.Streamable
{
  public paymentgateway.SecurePaymentProcessor value = null;

  public SecurePaymentProcessorHolder ()
  {
  }

  public SecurePaymentProcessorHolder (paymentgateway.SecurePaymentProcessor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = paymentgateway.SecurePaymentProcessorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    paymentgateway.SecurePaymentProcessorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return paymentgateway.SecurePaymentProcessorHelper.type ();
  }

}
